import Sidebar from '@/components/Sidebar'
import './globals.css'
import type { Metadata } from 'next'
import { Figtree } from 'next/font/google'
import ModalProvider from '@/providers/ModalProvider'
import UserProvider from '@/providers/UserProvider'
import ToastProvider from '@/providers/ToastProvider'
import AuthProvider from '@/providers/AuthProvider'
import getSongsByUserId from '@/actions/getSongsByUserId'
import { Player } from '@/components/Player'
import { Song } from '@/types'

const font = Figtree({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Spotify Clone',
  description: 'Generated by Bahar Keshavarz',
  icons: {
    icon: {
      url: "/favicon.ico",
      type: "image/ico",
    },
    shortcut: { url: "/favicon.ico", type: "image/ico" },
  },
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const songs= await getSongsByUserId();
  return (
    <html lang="en">
      <body className={font.className}>
       <ToastProvider/>
        <AuthProvider>
          <UserProvider>
            <ModalProvider/>
            <Sidebar songs={songs}>
              {children}
            </Sidebar>
            <Player/>
          </UserProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
